/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Model.Person;
import Model.Personhistory;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;

/**
 *
 * @author shreyasdasariicloud.com
 */
public class PersonRegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientRegisterJPanel
     */
    private JSplitPane SplitPane;
    Personhistory personHistory;
    
    public PersonRegisterJPanel(JSplitPane SplitPane, Personhistory personHistory) {
        initComponents();
        this.SplitPane = SplitPane;
        this.personHistory = personHistory;
    }
    
//    private static boolean isInteger(String s) {
//    try { 
//        Integer.parseInt(s); 
//    } 
//    catch(NumberFormatException | NullPointerException e) { 
//        return false; 
//    }
//    return true;
//    }
    
    // only got here if we didn't return false
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelPincode = new javax.swing.JLabel();
        LabelCellno = new javax.swing.JLabel();
        LabelEmailid = new javax.swing.JLabel();
        TxtName = new javax.swing.JTextField();
        TxtAge = new javax.swing.JTextField();
        TxtAddress = new javax.swing.JTextField();
        TxtGender = new javax.swing.JTextField();
        TxtCity = new javax.swing.JTextField();
        TxtPincode = new javax.swing.JTextField();
        TxtCellno = new javax.swing.JTextField();
        TxtEmailid = new javax.swing.JTextField();
        ComboGender = new javax.swing.JComboBox<>();
        LabelTitle = new javax.swing.JLabel();
        LabelName = new javax.swing.JLabel();
        LabelAge = new javax.swing.JLabel();
        LabelGender = new javax.swing.JLabel();
        LabelAddress = new javax.swing.JLabel();
        LabelCity = new javax.swing.JLabel();
        BtnLogin = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        LabelCreatePass = new javax.swing.JLabel();
        TxtPass = new javax.swing.JPasswordField();
        BtnSave = new javax.swing.JButton();

        LabelPincode.setText("Pincode:");

        LabelCellno.setText("Cell Phone Number:");

        LabelEmailid.setText("Email ID:");

        TxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNameActionPerformed(evt);
            }
        });

        TxtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAgeActionPerformed(evt);
            }
        });

        TxtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAddressActionPerformed(evt);
            }
        });

        TxtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtGenderActionPerformed(evt);
            }
        });

        TxtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCityActionPerformed(evt);
            }
        });

        TxtPincode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPincodeActionPerformed(evt);
            }
        });

        TxtCellno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCellnoActionPerformed(evt);
            }
        });

        ComboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Other", " " }));
        ComboGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboGenderActionPerformed(evt);
            }
        });

        LabelTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        LabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitle.setText("Person Registration");

        LabelName.setText("Name:");

        LabelAge.setText("Age:");

        LabelGender.setText("Gender:");

        LabelAddress.setText("Address:");

        LabelCity.setText("City:");

        BtnLogin.setText("Login");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });

        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        LabelCreatePass.setText("Create Password:");

        BtnSave.setText("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(BtnBack)
                        .addGap(18, 18, 18)
                        .addComponent(BtnSave)
                        .addGap(18, 18, 18)
                        .addComponent(BtnLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelName)
                                .addGap(92, 92, 92)
                                .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LabelCellno)
                                        .addComponent(LabelPincode, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(LabelEmailid, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(LabelGender)
                                            .addComponent(LabelAge)
                                            .addComponent(LabelAddress)
                                            .addComponent(LabelCity)
                                            .addComponent(LabelCreatePass))
                                        .addGap(4, 4, 4)))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TxtEmailid, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TxtAddress)
                                        .addComponent(TxtCity)
                                        .addComponent(TxtPincode)
                                        .addComponent(TxtCellno, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ComboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TxtAge, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TxtPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))))))
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelName)
                    .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelCreatePass)
                    .addComponent(TxtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAge)
                    .addComponent(TxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelGender)
                    .addComponent(TxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAddress)
                    .addComponent(TxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCity)
                    .addComponent(TxtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPincode)
                    .addComponent(TxtPincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCellno)
                    .addComponent(TxtCellno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEmailid)
                    .addComponent(TxtEmailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBack)
                    .addComponent(BtnLogin)
                    .addComponent(BtnSave))
                .addGap(92, 92, 92))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LabelTitle)
                    .addContainerGap(474, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNameActionPerformed

    private void TxtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAgeActionPerformed

    private void TxtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAddressActionPerformed

    private void TxtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtGenderActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TxtGenderActionPerformed

    private void TxtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCityActionPerformed

    private void TxtPincodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPincodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPincodeActionPerformed

    private void TxtCellnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCellnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCellnoActionPerformed

    private void ComboGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboGenderActionPerformed
        // TODO add your handling code here:
        String selectedValue = ComboGender.getSelectedItem().toString();
        TxtGender.setText(selectedValue);
    }//GEN-LAST:event_ComboGenderActionPerformed
    
    
    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        //closeWin();
        MainPageJPanel mp = new MainPageJPanel(SplitPane, personHistory);
        SplitPane.setRightComponent(mp);

    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        // TODO add your handling code here:
        PersonLoginJPanel personlogin = new PersonLoginJPanel(SplitPane, personHistory);
        SplitPane.setRightComponent(personlogin);
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:
        if (TxtName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Name field is Empty!");
        }
        else if (TxtPass.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Password field is Empty!");
        }
        else if (TxtAge.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Age field is Empty!");
        }
        else if(TxtGender.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Gender Field is empty");
        }
       else if(TxtAddress.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Address Field is empty");
        }
       else if(TxtCity.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "City Field is empty");
        }
       else if(TxtEmailid.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "EmailID Field is empty");
        }
//       else if(!isInteger(TxtAge.getText()))
//        {
//            JOptionPane.showMessageDialog(this, "Age Entered should be Integer");
//        }
       else if(Integer.parseInt(TxtAge.getText())>200)
        {
            JOptionPane.showMessageDialog(this, "Age Should not be over 200");
        }
       else if(!(TxtGender.getText().equals("Male") || TxtGender.getText().equals("Female") || TxtGender.getText().equals("male") || TxtGender.getText().equals("female")))
        {
            JOptionPane.showMessageDialog(this, "Gender Field Invalid");
        }
       else{
        String name = TxtName.getText();        
        //char[] password = TxtPass.getPassword();
        int age = Integer.parseInt(TxtAge.getText());
        String gender = TxtGender.getText();
        String address = TxtAddress.getText();
        String city = TxtCity.getText();
        int pincode = Integer.parseInt(TxtPincode.getText());
        int cellphoneno = Integer.parseInt(TxtCellno.getText());        
        String emailID = TxtEmailid.getText();
        
        Person ps = personHistory.addNewPerson();
        
        ps.setName(name);
        //p.setPassword(p);
        ps.setAge(age);
        ps.setGender(gender);
        ps.setAddress(address);
        ps.setCity(city);
        ps.setPincode(pincode);
        ps.setCellphoneno(cellphoneno);
        ps.setEmailID(emailID);
        
        JOptionPane.showMessageDialog(this, "New Record Added!");
        
        TxtName.setText("");
        TxtPass.setText("");
        TxtAge.setText("");
        TxtGender.setText("");
        TxtAddress.setText("");
        TxtCity.setText("");
        TxtPincode.setText("");
        TxtCellno.setText("");
        TxtEmailid.setText("");
       }
        
    }//GEN-LAST:event_BtnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnLogin;
    private javax.swing.JButton BtnSave;
    private javax.swing.JComboBox<String> ComboGender;
    private javax.swing.JLabel LabelAddress;
    private javax.swing.JLabel LabelAge;
    private javax.swing.JLabel LabelCellno;
    private javax.swing.JLabel LabelCity;
    private javax.swing.JLabel LabelCreatePass;
    private javax.swing.JLabel LabelEmailid;
    private javax.swing.JLabel LabelGender;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelPincode;
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JTextField TxtAddress;
    private javax.swing.JTextField TxtAge;
    private javax.swing.JTextField TxtCellno;
    private javax.swing.JTextField TxtCity;
    private javax.swing.JTextField TxtEmailid;
    private javax.swing.JTextField TxtGender;
    private javax.swing.JTextField TxtName;
    private javax.swing.JPasswordField TxtPass;
    private javax.swing.JTextField TxtPincode;
    // End of variables declaration//GEN-END:variables
}
