/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Model.PatientHistory;
import Model.Person;
import Model.Personhistory;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;

/**
 *
 * @author shreyasdasariicloud.com
 */
public class RegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterJPanel
     */
    private JSplitPane SplitPane;
    Personhistory personHistory;
    //PatientHistory patientHistory;
    public RegisterJPanel(JSplitPane SplitPane, Personhistory personHistory) {
        initComponents();
        this.SplitPane = SplitPane;
        this.personHistory = personHistory;
        //this.patientHistory = patientHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTitle = new javax.swing.JLabel();
        LabelName = new javax.swing.JLabel();
        LabelAge = new javax.swing.JLabel();
        LabelGender = new javax.swing.JLabel();
        LabelAddress = new javax.swing.JLabel();
        LabelCity = new javax.swing.JLabel();
        LabelPincode = new javax.swing.JLabel();
        LabelCellno = new javax.swing.JLabel();
        LabelEmailid = new javax.swing.JLabel();
        LabelPatient = new javax.swing.JLabel();
        TxtName = new javax.swing.JTextField();
        TxtAge = new javax.swing.JTextField();
        TxtAddress = new javax.swing.JTextField();
        TxtGender = new javax.swing.JTextField();
        TxtCity = new javax.swing.JTextField();
        TxtPincode = new javax.swing.JTextField();
        TxtCellno = new javax.swing.JTextField();
        TxtEmailid = new javax.swing.JTextField();
        TxtPatient = new javax.swing.JTextField();
        ComboGender = new javax.swing.JComboBox<>();
        ComboPatient = new javax.swing.JComboBox<>();
        LabelDoctor = new javax.swing.JLabel();
        LabelPatient2 = new javax.swing.JLabel();
        ComboDoctor = new javax.swing.JComboBox<>();
        TxtDoctor = new javax.swing.JTextField();
        BtnBack = new javax.swing.JButton();
        Book = new com.toedter.calendar.JCalendar();
        TxtBookappointment = new javax.swing.JTextField();
        BtnSave = new javax.swing.JButton();
        BtnLogin = new javax.swing.JButton();

        LabelTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        LabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitle.setText("Patient Registration");

        LabelName.setText("Name:");

        LabelAge.setText("Age:");

        LabelGender.setText("Gender:");

        LabelAddress.setText("Address:");

        LabelCity.setText("City:");

        LabelPincode.setText("Pincode:");

        LabelCellno.setText("Cell Phone Number:");

        LabelEmailid.setText("Email ID:");

        LabelPatient.setText("Are you a Patient?:");

        TxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNameActionPerformed(evt);
            }
        });

        TxtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAgeActionPerformed(evt);
            }
        });

        TxtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAddressActionPerformed(evt);
            }
        });

        TxtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtGenderActionPerformed(evt);
            }
        });

        TxtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCityActionPerformed(evt);
            }
        });

        TxtPincode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPincodeActionPerformed(evt);
            }
        });

        TxtCellno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCellnoActionPerformed(evt);
            }
        });

        TxtPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPatientActionPerformed(evt);
            }
        });

        ComboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Other", " " }));
        ComboGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboGenderActionPerformed(evt);
            }
        });

        ComboPatient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Yes", "No" }));

        LabelDoctor.setText("Select Doctor:");

        LabelPatient2.setText("Book an Appointment:");

        ComboDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "ABC", "XYZ", "UVW", "EFG" }));

        TxtDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDoctorActionPerformed(evt);
            }
        });

        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        TxtBookappointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBookappointmentActionPerformed(evt);
            }
        });

        BtnSave.setText("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        BtnLogin.setText("Login");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelPatient2)
                    .addComponent(LabelDoctor)
                    .addComponent(LabelPatient)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelCellno)
                        .addComponent(LabelPincode, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LabelEmailid, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelName)
                            .addComponent(LabelGender)
                            .addComponent(LabelAge)
                            .addComponent(LabelAddress)
                            .addComponent(LabelCity))
                        .addGap(4, 4, 4)))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Book, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtBookappointment, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ComboPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ComboDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtDoctor))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtEmailid, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TxtAddress)
                                .addComponent(TxtCity)
                                .addComponent(TxtPincode)
                                .addComponent(TxtCellno, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(BtnBack)
                .addGap(18, 18, 18)
                .addComponent(BtnSave)
                .addGap(18, 18, 18)
                .addComponent(BtnLogin)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitle)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelName)
                    .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAge)
                    .addComponent(TxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelGender)
                    .addComponent(TxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAddress)
                    .addComponent(TxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCity)
                    .addComponent(TxtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPincode)
                    .addComponent(TxtPincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCellno)
                    .addComponent(TxtCellno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEmailid)
                    .addComponent(TxtEmailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPatient)
                    .addComponent(TxtPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDoctor)
                    .addComponent(ComboDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Book, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPatient2)
                    .addComponent(TxtBookappointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBack)
                    .addComponent(BtnSave)
                    .addComponent(BtnLogin))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNameActionPerformed

    private void TxtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAgeActionPerformed

    private void TxtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAddressActionPerformed

    private void TxtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtGenderActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TxtGenderActionPerformed

    private void TxtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCityActionPerformed

    private void TxtPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPatientActionPerformed

    private void TxtDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDoctorActionPerformed

    private void TxtPincodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPincodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPincodeActionPerformed

    private void TxtCellnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCellnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCellnoActionPerformed

    private void TxtBookappointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBookappointmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBookappointmentActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        //closeWin();
        MainPageJPanel mp = new MainPageJPanel(SplitPane, personHistory);
        SplitPane.setRightComponent(mp);
        
        
       
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:
        String name = TxtName.getText();
        int age = Integer.parseInt(TxtAge.getText());
        String gender = TxtGender.getText();
        String address = TxtAddress.getText();
        String city = TxtCity.getText();
        int pincode = Integer.parseInt(TxtPincode.getText());
        int cellphoneno = Integer.parseInt(TxtCellno.getText());
        String emailID = TxtEmailid.getText();
        
                          
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void ComboGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboGenderActionPerformed
        // TODO add your handling code here:
        String selectedValue = ComboGender.getSelectedItem().toString();
        TxtGender.setText(selectedValue);
    }//GEN-LAST:event_ComboGenderActionPerformed

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        // TODO add your handling code here:
        PatientLoginJPanel patientLogin = new PatientLoginJPanel(SplitPane, personHistory);
        SplitPane.setRightComponent(patientLogin);
        
    }//GEN-LAST:event_BtnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar Book;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnLogin;
    private javax.swing.JButton BtnSave;
    private javax.swing.JComboBox<String> ComboDoctor;
    private javax.swing.JComboBox<String> ComboGender;
    private javax.swing.JComboBox<String> ComboPatient;
    private javax.swing.JLabel LabelAddress;
    private javax.swing.JLabel LabelAge;
    private javax.swing.JLabel LabelCellno;
    private javax.swing.JLabel LabelCity;
    private javax.swing.JLabel LabelDoctor;
    private javax.swing.JLabel LabelEmailid;
    private javax.swing.JLabel LabelGender;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelPatient;
    private javax.swing.JLabel LabelPatient2;
    private javax.swing.JLabel LabelPincode;
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JTextField TxtAddress;
    private javax.swing.JTextField TxtAge;
    private javax.swing.JTextField TxtBookappointment;
    private javax.swing.JTextField TxtCellno;
    private javax.swing.JTextField TxtCity;
    private javax.swing.JTextField TxtDoctor;
    private javax.swing.JTextField TxtEmailid;
    private javax.swing.JTextField TxtGender;
    private javax.swing.JTextField TxtName;
    private javax.swing.JTextField TxtPatient;
    private javax.swing.JTextField TxtPincode;
    // End of variables declaration//GEN-END:variables

    public void systemExit() {
        //WindowEvent winClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        //Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }

    
 
    
}
